name: Update README Time

on:
  schedule:
    - cron: "0 * * * *"  # 每小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README timestamp
        run: |
          TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          sed -i "s/<!-- TIME_PLACEHOLDER -->/${TIME}/g" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "Jeffrey"
          git config --global user.email "support@metrovpn.xyz"
          git add README.md
          git commit -m "Update offer information" || exit 0
          git push
